apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-f1b2
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0007-tenant/tkrw-pr714-0075-0007-app/devfile-sample-f1b2@sha256:e1b25ea715d99795810daf81e0363e9e822d94da17bdf609ce9cd0973c1786c6
        name: my-nodejs
        resources: {}
status: {}
